version: "3.9"

services:
  frontend:
    build:
      context: ..
      dockerfile: breezy-infra/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000/api
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - breezy-network
    command: pnpm start

  backend:
    build:
      context: ..
      dockerfile: breezy-infra/Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://daemxnn:5i1LyxzizSSWBGku@breezy.zvevcc8.mongodb.net/
      - JWT_SECRET=dev_secret_jwt
    networks:
      - breezy-network
    command: pnpm start

networks:
  breezy-network:
    driver: bridge

volumes:
  mongodb_data: